site: #Hargill, TX
  data:
    lat: 26.175 # 26.4430
    lon: -98.284 # -98.0138
    elev: 1099
    year: 2013
    tz: -6
    site_boundaries: 
      verts:  
        - [0.0, 0.0]
        - [0.0, 20000.0]
        - [20000.0, 20000.0]
        - [20000.0, 0.0] 
      verts_simple: 
        - [0.0, 0.0]
        - [0.0, 20000.0]
        - [20000.0, 20000.0]
        - [20000.0, 0.0]
  solar_resource_file: ""
  wind_resource_file: ""
  wave_resource_file: ""
  grid_resource_file: ""
  hub_height: 80.0
  capacity_hours: []
  solar: true
  wind: true
  wave: false
  wind_resource_origin: "WTK"
  

technologies:
  wind:
    num_turbines: 300 #max num turbines INL used 900 reduce size by 3
    turbine_rating_kw: 2000.0
    fin_model: !include default_fin_config.yaml
  pv:
    system_capacity_kw: 566667 #reduce size by 3 1700000
    dc_degradation: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    fin_model: !include default_fin_config.yaml
  battery:
    system_capacity_kwh: 39700 #reduce size by 3  119100 #assume 4hr battery
    system_capacity_kw:  9925 ##29775 
    minimum_SOC: 20.0
    maximum_SOC: 100.0
    initial_SOC: 90.0
    fin_model: !include default_fin_config.yaml
  grid:
    interconnect_kw: 2000000000 # Set higher than rated generation capacity
    fin_model: !include default_fin_config.yaml

config:
  simulation_options:
    wind:
      skip_financial: false
  dispatch_options:
    battery_dispatch: load_following_heuristic # load_following_heuristic #heuristic
    solver: cbc
    n_look_ahead_periods: 48
    grid_charging: false
    pv_charging_only: false
    include_lifecycle_count: false
  cost_info: # Costs from GS Manuscript Supplemental Table S11
    wind_installed_cost_mw: 1300000 # (2020USD) 
    solar_installed_cost_mw: 883000 # (2020USD) 
    storage_installed_cost_mwh: 345000 # (2020USD) 
    storage_installed_cost_mw: 250000 # (2020USD) 
    wind_om_per_kw: 0.20833 # (2020USD) 
    pv_om_per_kw:  0.1833 # (2020USD) 
    battery_om_per_kw: 0 #9.25 # (2020USD) based on 0.025 percent of battery capex with a 100MW 1hr battery
